- name: Install and Start Nginx
  hosts: linux_mint
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started
      service:
        name: nginx
        state: started
        enabled: true
